[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_20"]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php82 artisan migrate --force",
  "php82 artisan db:seed --force || true",
  "php82 artisan config:cache",
  "php82 artisan route:cache",
  "php82 artisan view:cache"
]

[phases.build]
cmds = ["npm install", "npm run build"]

[start]
cmd = "php82 artisan serve --host=0.0.0.0 --port=$PORT"