[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "nodejs_20"]

[phases.install]
cmds = [
  "cd capstone_backend && composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "bash start.sh"