[phases.setup]
nixPkgs = ["php", "phpPackages.composer", "nodejs_20"]

[phases.install]
cmds = [
  "cd capstone_backend && composer install --no-dev --optimize-autoloader"
]

[start]
cmd = "cd capstone_backend && php artisan serve --host=0.0.0.0 --port=$PORT"